language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

before_install:
  - go get -u golang.org/x/tools/cmd/cover
  - if [[ $TRAVIS_GO_VERSION == 1.6* ]]; then go get -u golang.org/x/lint/golint; fi
  - go get -u golang.org/x/tools/cmd/vet

script:
  - make gofmt
  - if type "golint" > /dev/null; then make golint; fi
  - make govet
  - make test
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
